title: "EDWARD MUGISHA"
author: "Edward Mugisha"
description: "My Portfolio"
permalink: /https://mugisha112.github.io/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: false        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {title: LinkedIn, icon: linkedin, url: "http://www.linkedin.com/in/edwardlmugisha"}
  - {title: Github, icon: github, url: "https://github.com/Mugisha112"}
  - {title: Mail, icon: envelope, url: "mailto:eddwardmugisha@gmail.com"}
  - {title: "Tableau", url: "https://public.tableau.com/app/profile/edwardlmugisha"}
  - {file: "mavenpost.md", title: "Projects"}
  - {file: "resume.md", title: "CV"}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Back to the Top,  url: "https://mugisha112.github.io"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
